# Generated by Django 5.2 on 2025-05-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='anime_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_url',
            field=models.CharField(max_length=500),
        ),
    ]
