# Generated by Django 5.2 on 2025-05-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0003_movie_thumbnail_alter_movie_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_url',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(default=1, upload_to='movies/'),
            preserve_default=False,
        ),
    ]
