# Generated by Django 5.2 on 2025-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0004_remove_movie_video_url_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='movies/1080p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='movies/360p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='movies/720p/'),
        ),
    ]
