# Generated by Django 5.2 on 2025-05-04 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0005_movie_video_1080p_movie_video_360p_movie_video_720p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
    ]
