# Generated by Django 5.2 on 2025-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0006_remove_movie_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='typeOF',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
