# Generated by Django 5.2 on 2025-05-04 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0007_movie_typeof_alter_movie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('typeOF', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='typeOF',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал')], max_length=10),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_360p', models.FileField(blank=True, null=True, upload_to='series/360p/')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='series/720p/')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to='series/1080p/')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movietheater.series')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('series', 'episode_number')},
            },
        ),
    ]
