# Generated by Django 5.2 on 2025-05-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0008_series_alter_movie_thumbnail_alter_movie_typeof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='typeOF',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('video', 'Видео')], max_length=10),
        ),
        migrations.AlterField(
            model_name='series',
            name='typeOF',
            field=models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('video', 'Видео')], max_length=10),
        ),
    ]
