# Generated by Django 5.2 on 2025-05-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0009_alter_movie_typeof_alter_series_typeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
                ('typeOF', models.CharField(choices=[('movie', 'Фильм'), ('series', 'Сериал'), ('video', 'Видео')], max_length=10)),
                ('video_360p', models.FileField(blank=True, null=True, upload_to='movies/360p/')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='movies/720p/')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to='movies/1080p/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
