# Generated by Django 5.2 on 2025-05-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='author',
            field=models.CharField(blank=True, null=True),
        ),
    ]
