# Generated by Django 5.2 on 2025-05-18 10:11

import movietheater.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0012_movie_poster_series_poster_video_poster_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=movietheater.models.user_avatar_path, verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
