# Generated by Django 5.2 on 2025-05-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0014_movie_average_rating_series_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='series',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='video',
            name='average_rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
