# Generated by Django 5.2 on 2025-05-19 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietheater', '0016_movierating_seriesrating_videorating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50)),
                ('content_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('favorite', 'Избранное'), ('watched', 'Просмотрено'), ('watchlist', 'Смотреть позже')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'content_type', 'status'], name='movietheate_user_id_1da87c_idx')],
                'unique_together': {('user', 'content_type', 'content_id', 'status')},
            },
        ),
    ]
